#!/usr/bin/env ruby

class LogIndenter
  def process
    # e.g. 2022-08-09 13:27:19.538613Z INFO [1:Base.FOLLOWER] - Leader ID is changed to 3
    line_pattern = /^(?<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d{6}Z)\s+(?<level>\w+)\s+\[(?<node>\d+):(?<mode>.*)\]\s+-\s+(?<content>.*)/

    STDIN.each_line do |line|
      unless m = line_pattern.match(line)
        raise "Unexpected line format: #{line}"
      end
      captured = m.named_captures
      node_index = Integer(captured['node'])
      
      print captured['timestamp']
      print "\t" * node_index
      puts "[#{captured['node']}:#{captured['mode']}] #{captured['content']}"
    end
  end
end

if $0 == __FILE__
  # Usage: head -1000 -q oraft-*/oraft.log | sort | somewhere/oraft/tool/log-indent > indented-log.txt
  #   or   cat oraft-*/oraft.log | sort | somewhere/oraft/tool/log-indent > indented-log.txt
  LogIndenter.new.process
end

